LDFLAGS = -lm
SOURCES = $(find . -name "*.c")
Numbersystem = 
all:	$(SOURCES)
	cc $(LDFLAGS) Projects/BinaryToString.c -o Out/BinaryString
	cc $(LDFLAGS) Projects/FactorsLister.c -o Out/FactorsLister
	cc $(LDFLAGS) Projects/SimpleInterestCalculator.c -o Out/SimpleInterestCalculator
	cc $(LDFLAGS) Projects/TextToBinary.c -o Out/TextToBinary
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToHexadecimal.c -o Out/BinaryToHexadecimal
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToDecimal.c -o Out/BinaryToDecimal
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToOctal.c -o Out/BinaryToOctal
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToBinary.c -o Out/DecimalToBinary
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToHexadecimal.c -o Out/DecimalToHexadecimal
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToOctal.c -o Out/DecimalToOctal
	cc $(LDFLAGS) Projects/NumberSystem/OctalToBinary.c -o Out/OctalToBinary
	cc $(LDFLAGS) Projects/NumberSystem/OctalToDecimal.c -o Out/OctalToDecimal
	cc $(LDFLAGS) Projects/NumberSystem/OctalToHexadecimal.c -o Out/OctalToDecimal
numbersystem: 
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToHexadecimal.c -o Out/BinaryToHexadecimal
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToDecimal.c -o Out/BinaryToDecimal
	cc $(LDFLAGS) Projects/NumberSystem/BinaryToOctal.c -o Out/BinaryToOctal
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToBinary.c -o Out/DecimalToBinary
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToHexadecimal.c -o Out/DecimalToHexadecimal
	cc $(LDFLAGS) Projects/NumberSystem/DecimalToOctal.c -o Out/DecimalToOctal
	cc $(LDFLAGS) Projects/NumberSystem/OctalToBinary.c -o Out/OctalToBinary
	cc $(LDFLAGS) Projects/NumberSystem/OctalToDecimal.c -o Out/OctalToDecimal
	cc $(LDFLAGS) Projects/NumberSystem/OctalToHexadecimal.c -o Out/OctalToDecimal

